# render.yaml
services:
  - type: web
    name: github-oauth-proxy
    env: node
    plan: free
    buildCommand: npm install && npx prisma generate
    startCommand: npx ts-node src/server.ts
    envVars:
      - key: GITHUB_CLIENT_ID
        sync: false
      - key: GITHUB_CLIENT_SECRET
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: your-database-name
          property: connectionString
      - key: JWT_SECRET
        sync: false
      - key: ALLOWED_ORIGINS
        sync: false
      - key: REDIRECT_URI
        sync: false
databases:
  - name: your-database-name
    plan: free